// Gemini API Client for AI Studio

const GEMINI_API_KEY = process.env.GEMINI_IMAGE_API || process.env.GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
  console.error('GEMINI_IMAGE_API environment variable is not set');
}
const GEMINI_MODEL = 'gemini-2.5-flash-image';
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

export interface GeminiGenerationConfig {
  temperature?: number;
  topP?: number;
  topK?: number;
  maxOutputTokens?: number;
  responseModalities?: string[];
}

export interface GeminiRequest {
  contents: {
    parts: Array<{
      text?: string;
      inlineData?: {
        mimeType: string;
        data: string;
      };
    }>;
  }[];
  generationConfig?: GeminiGenerationConfig;
}

export interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
        inlineData?: {
          mimeType: string;
          data: string;
        };
      }>;
    };
    finishReason?: string;
  }>;
  error?: {
    code: number;
    message: string;
    status: string;
  };
}

/**
 * Generate an edited image using Gemini's image generation model
 */
export async function generateImage(
  imageBase64: string,
  prompt: string,
  mimeType: string = 'image/png'
): Promise<{ success: true; imageBase64: string; mimeType: string } | { success: false; error: string }> {
  try {
    // Clean up base64 if it has data URI prefix
    const cleanBase64 = imageBase64.includes(',') 
      ? imageBase64.split(',')[1] 
      : imageBase64;
    
    // Detect mime type from data URI if present
    let detectedMimeType = mimeType;
    if (imageBase64.startsWith('data:')) {
      const match = imageBase64.match(/data:([^;]+);/);
      if (match) {
        detectedMimeType = match[1];
      }
    }

    const request: GeminiRequest = {
      contents: [
        {
          parts: [
            {
              text: prompt,
            },
            {
              inlineData: {
                mimeType: detectedMimeType,
                data: cleanBase64,
              },
            },
          ],
        },
      ],
      generationConfig: {
        responseModalities: ['Text', 'Image'],
      },
    };

    const response = await fetch(`${GEMINI_ENDPOINT}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error response:', errorText);
      return {
        success: false,
        error: `Gemini API error: ${response.status} ${response.statusText}`,
      };
    }

    const data: GeminiResponse = await response.json();

    if (data.error) {
      return {
        success: false,
        error: `Gemini API error: ${data.error.message}`,
      };
    }

    // Extract generated image from response
    const candidates = data.candidates || [];
    if (candidates.length === 0) {
      return {
        success: false,
        error: 'No candidates returned from Gemini',
      };
    }

    const parts = candidates[0]?.content?.parts || [];
    
    // Find the image part
    const imagePart = parts.find(part => part.inlineData);
    
    if (!imagePart?.inlineData) {
      // Log what we got for debugging
      const textPart = parts.find(part => part.text);
      console.error('Gemini response parts:', JSON.stringify(parts.map(p => ({
        hasText: !!p.text,
        hasInlineData: !!p.inlineData,
        textPreview: p.text?.substring(0, 100)
      }))));
      
      return {
        success: false,
        error: textPart?.text || 'No image generated by Gemini',
      };
    }

    return {
      success: true,
      imageBase64: imagePart.inlineData.data,
      mimeType: imagePart.inlineData.mimeType,
    };
  } catch (error) {
    console.error('Gemini generation error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

/**
 * Health check for Gemini API
 */
export async function checkGeminiHealth(): Promise<boolean> {
  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}?key=${GEMINI_API_KEY}`
    );
    return response.ok;
  } catch {
    return false;
  }
}
